# Metadata
title:          Rafaell Lycan
description:    >
                This is my localhost, where I (randomly) write about programming, the web, life and/or photography.
keys:           desenvolvedor, front end, back end, developer, php, javascript, node, laravel, angular, react, software
logo:           https://avatars2.githubusercontent.com/u/499192
url:            http://mikefowler.me
repository:     mikefowler/mikefowler.github.io
rss:            http://feeds.feedburner.com/MikeFowler
lang:           pt_BR

# Author Informations
author:
  name:         Rafaell Lycan
  first_name:   Rafaell
  last_name:    Lycan
  email:        sonny.webdsg@gmail
  location:     barcelona
  twitter:      rafaelllycan
  github:       rafaell-lycan
  gravatar:     dd1c977c7a3e384a9cdae3b5ddd9b006

# Config
config:
  g_analytics:  UA-16383035-5
  g_verify:     Abc123Def456
  disqus_name:  rafaelllycan
  theme_color:  "#5fbffd"

webmaster_verifications:
  google: Abc123Def456

navigation:
  - text: Home
    url: /
  - text: Articles
    url: /articles
  - text: About
    url: /about


social:
  name:         Rafaell Lycan
  links:
    - https://twitter.com/RafaellLycan
    - https://www.facebook.com/rafaell.lycan
    - https://github.com/rafaell-lycan
    - http://instagram.com/rafaelllycan
    - https://www.linkedin.com/in/rafaelllycan/
    - https://keybase.io/rafaell
    - https://plus.google.com/+RafaellLycan

twitter:
  username:     RafaellLycan

facebook:
  app_id:       1160764874037367

github:
  url: http://rafaell-lycan.com

# Collections
collections:
  trips:
    output: false
    permalink: /trips/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "trips"
    values:
      layout: trip

# Paths
baseurl: ""
asset_path:     "assets"

# Conversion
markdown:       kramdown
highlighter:    rouge
kramdown:
  input:        GFM
  syntax_highlighter: rouge
  parse_block_html: true

sass:
  sass_dir:     _sass
  style:        :compressed

# Output
permalink:      /:year/:title/
paginate:       10
paginate_path:  "/articles/page/:num/"
livereload:     false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-pagination
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata

# Reading
exclude:
  - src
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - README.md
  - _archive
  - _scripts

# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   profile: false
#   startings: [body]
