# Metadata
title:          Hi there, I'm Rafaell
description:    Web development, front end stuff, tutorials for beginners and more by Rafaell Lycan
keys:           desenvolvedor, front end, back end, developer, php, javascript, node, laravel, angular, react, software
logo:           /assets/icons/favicon-192x192.png
url:            http://mikefowler.me
repository:     mikefowler/mikefowler.github.io
rss:            http://feeds.feedburner.com/MikeFowler

# Author Informations
author:
  name:         Rafaell Lycan
  first_name:   Rafaell
  last_name:    Lycan
  email:        sonny.webdsg@gmail
  location:     barcelona
  twitter:      rafaelllycan
  github:       rafaell-lycan
  gravatar:     dd1c977c7a3e384a9cdae3b5ddd9b006
  plus:         https://plus.google.com/+RafaellLycan

# Config
config:
  g_analytics:  UA-16383035-5
  g_verify:     Abc123Def456
  disqus_name:  rafaelllycan

navigation:
  - text: About
    url: /about

# Collections
collections:
  trips:
    output: false
    permalink: /trips/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "trips"
    values:
      layout: trip

# Paths
baseurl: ""
asset_path:     "assets"

# Conversion
markdown:       kramdown
highlighter:    rouge
kramdown:
  input:        GFM
  syntax_highlighter: rouge
  parse_block_html: true

sass:
  sass_dir:     _sass
  style:        :compressed

# Output
permalink:      /:year/:title/
paginate:       100
paginate_path:  "/page/:num/"
livereload:     false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-pagination
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata

# Reading
exclude:
  - src
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - README.md
  - _archive
  - _scripts

# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   profile: false
#   startings: [body]
